In [3]:
#Ch01: Linear Algebra

x= 1
y= 1.0
z= 1+1j
#%%
aList= [1,2,3]
aSet=  {10,20,30}
aDict= {'a':1, 'b':2, 'c':3}

In [5]:
import numpy as np

v= [10, 20, 30]
v= np.array(v)

A= [[1, 2, 3],
    [4, 5, 6]]
A= np.array(A)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
v1= [10, 20, 30]
v2= [40, 50, 60]

v1= np.array(v1)
v2= np.array(v2)
#%%
B= np.arange(2*3*4)
#%%
B= B.reshape(2,3,4)
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
import sympy as sy
x,y,z= sy.symbols('x,y,z')

from sympy import MatrixSymbol, Matrix

In [15]:
# Solve linear equations
########################

A= [[1,-2],
    [2, 1]]
A= np.array(A)

b= [1,7]
b= np.array(b)
b= b.reshape(2,1)

#[sol]
x= np.linalg.solve(A,b)
print(x)
# 驗算
A@x == b 
print(np.isclose(A@x, b))

# [sol2[]

x1= np.linalg.inv(A) @ b
print(x1)
# 驗算
A@x1 == b
print(np.isclose(A@x1, b)) 

[[3.]
 [1.]]
[[ True]
 [ True]]
[[3.]
 [1.]]
[[ True]
 [ True]]


In [19]:
# n 變數 線性方程組

n= 3 #np.random.randint(2,10)

np.random.seed(0)
A= np.random.randint(-5,5,size=(n,n))

np.random.seed(1)
b= np.random.randint(-5,5,size=(n,1))

x= np.linalg.solve(A, b)

print(
f'''
n= 
{n}, 
A= 
{A}
b= 
{b}
x= 
{x}
''')


n= 
3, 
A= 
[[ 0 -5 -2]
 [-2  2  4]
 [-2  0 -3]]
b= 
[[0]
 [3]
 [4]]
x= 
[[-1.75806452]
 [ 0.06451613]
 [-0.16129032]]



In [20]:
invA= np.linalg.inv(A)

x1= invA @ b

print(
f'''
n= 
{n}, 
A= 
{A}
invA=
{invA}
b= 
{b}
x1= 
{x1}
''')

#%%
# 驗算
validation= np.isclose(A@x, b)
print(validation)

validation= np.isclose(A@x1, b)
print(validation)


n= 
3, 
A= 
[[ 0 -5 -2]
 [-2  2  4]
 [-2  0 -3]]
invA=
[[-0.09677419 -0.24193548 -0.25806452]
 [-0.22580645 -0.06451613  0.06451613]
 [ 0.06451613  0.16129032 -0.16129032]]
b= 
[[0]
 [3]
 [4]]
x1= 
[[-1.75806452]
 [ 0.06451613]
 [-0.16129032]]

[[ True]
 [ True]
 [ True]]
[[ True]
 [ True]
 [ True]]


In [22]:
# HomeWork:
# 自己寫一個遞迴式的 function，來計算 Determinant 


n= 4 

np.random.seed(0)
A= np.random.randint(-5,5,size=(n,n))
print(f'A= \n{A}')

det= np.linalg.det(A)
print(f'det= {det}')


A= 
[[ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [-3 -1  2  1]
 [ 3  3 -4  1]]
det= -63.99999999999998


In [25]:
#Determinant

i= 0
det= 0
for j in range(n):
    Bi=  np.delete(A, i, axis=0)
    Bij= np.delete(Bi,j, axis=1)
    Bij= np.linalg.det(Bij)
    Aij= A[i,j]*Bij*(-1)**(i+j)
    det += Aij
print(f'det= {det}')

#%%

j= 0
det= 0
for i in range(n):
    Bj=  np.delete(A, j, axis=1)
    Bij= np.delete(Bj,i, axis=0)
    Bij= np.linalg.det(Bij)
    Aij= A[i,j]*Bij*(-1)**(i+j)
    det += Aij
print(f'det= {det}')

#%%

det= -64.00000000000003
det= -63.99999999999996


In [26]:
# when n is large, it is very slow!!

def ryDet(A):
    
    n= A.shape[0]
    if n>1:
        i= 0
        det= 0
        for j in range(n):
            Bi=  np.delete(A, i, axis=0)
            Bij= np.delete(Bi,j, axis=1)
            
            Bij= ryDet(Bij) #np.linalg.det(Bij)
            
            Aij= A[i,j]*Bij*(-1)**(i+j)
            det += Aij
        #print(f'det= {det}')
        return det
    
    elif A.shape[0]==1:
        det= A[0,0]
        return det
    else:
        return None

det= ryDet(A)
print(f'det= {det}')

det= -64


In [27]:
# when n is large, it is very slow!!

print(f'A= \n{A}')

def ryDet(A):
    
    n= A.shape[0]
    if n>1:
        i= 0
        Bi=  np.delete(A, i, axis=0)
        #print(f'\ni= {i}, Bi= \n{Bi}')
        
        det= 0
        for j in range(n):
            
            Bij= np.delete(Bi,j, axis=1)
            print(f'\ni,j= {i}{j}, Bij= \n{Bij}')
            
            Dij= ryDet(Bij) #np.linalg.det(Bij)
            print(f'.... Dij= {Dij}')
            
            Cij= A[i,j]*Dij*(-1)**(i+j)
            det += Cij
        #print(f'det= {det}')
        return det
    
    elif A.shape[0]==1:
        det= A[0,0]
        return det
    else:
        return None

det= ryDet(A)
print(f'\ndet= {det}')

A= 
[[ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [-3 -1  2  1]
 [ 3  3 -4  1]]

i,j= 00, Bij= 
[[ 4 -2  0]
 [-1  2  1]
 [ 3 -4  1]]

i,j= 00, Bij= 
[[ 2  1]
 [-4  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[-4]]
.... Dij= -4
.... Dij= 6

i,j= 01, Bij= 
[[-1  1]
 [ 3  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[3]]
.... Dij= 3
.... Dij= -4

i,j= 02, Bij= 
[[-1  2]
 [ 3 -4]]

i,j= 00, Bij= 
[[-4]]
.... Dij= -4

i,j= 01, Bij= 
[[3]]
.... Dij= 3
.... Dij= -2
.... Dij= 16

i,j= 01, Bij= 
[[ 2 -2  0]
 [-3  2  1]
 [ 3 -4  1]]

i,j= 00, Bij= 
[[ 2  1]
 [-4  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[-4]]
.... Dij= -4
.... Dij= 6

i,j= 01, Bij= 
[[-3  1]
 [ 3  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[3]]
.... Dij= 3
.... Dij= -6

i,j= 02, Bij= 
[[-3  2]
 [ 3 -4]]

i,j= 00, Bij= 
[[-4]]
.... Dij= -4

i,j= 01, Bij= 
[[3]]
.... Dij= 3
.... Dij= 6
.... Dij= 0

i,j= 02, Bij= 
[[ 2  4  0]
 [-3 -1  1]
 [ 3  3  1]]

i,j= 00, Bij= 
[[-1  1]
 [ 3  1]]

i,j= 00, Bij= 

In [28]:
import scipy.linalg

A= [[4,3],
    [6,3]]

'''
A= [[12, -51, 4], 
    [6, 167, -68],
    [-4, 24, -41]]
'''

A= np.array(A)

P,L,U= scipy.linalg.lu(A)

# 驗算
P @ L @ U == A
np.isclose(P @ L @ U , A)
np.allclose(P @ L @ U , A)


True

In [30]:
Q,R= scipy.linalg.qr(A)

# 驗算
(Q @ R == A).all()

np.allclose(Q @ R , A)

# 再檢查 Q 的正交性質
#assert Q[0]@Q[1] == 0
#assert Q[0]@Q[0] == 1
assert np.allclose(Q[0]@Q[1] , 0)
assert np.allclose(Q[0]@Q[0] , 1)

#%%
λ, Q= scipy.linalg.eig(A)

lmbd= λ 
# 驗算
#assert A @ Q[:,0] == Q[:,0] * λ[0]

assert np.allclose(A @ Q[:,0], Q[:,0] * λ[0] )

assert np.allclose(A @ Q, Q @ np.diag(λ) )
#%%
U, σ, V_T= scipy.linalg.svd(A)

V= V_T.T

Σ= np.diag(σ)

sigma= σ
Sigma= Σ 

# 驗算

assert np.allclose(U @  Σ @ V.T, A )

# 再檢查 U, V 的正交性質

assert np.allclose(U[0]@U[1] , 0)
assert np.allclose(V[0]@V[1] , 0)
assert np.allclose(U[0]@U[0] , 1)
assert np.allclose(V[0]@V[0] , 1)

#
# 檢查 orthogonal , orthonormal
#
assert np.allclose(U@U.T, np.eye(U.shape[0]))
assert np.allclose(V@V.T, np.eye(V.shape[0]))

#
assert np.allclose(A  @V, U@Σ)
assert np.allclose(A.T@U, V@Σ)


In [31]:
import numpy as np
import scipy.linalg as sp_linalg

M= [[1,2],
    [3,4]]
M= np.array(M)
U,sigma,V_T= np.linalg.svd(M)
V= V_T.T
MtM= M.T@M
ld, Q= np.linalg.eig(MtM)
#%%

A= [[12, -51, 4], 
    [6, 167, -68],
    [-4, 24, -41]]
A= np.array(A)
Q,R= np.linalg.qr(A)

#%%
A= [[2,1],
    [1,2]]
A= np.array(A)
lmda, eigV= np.linalg.eig(A)
#%%

Q, R= np.linalg.qr(A)

#%%
U,Sigma,V_T= np.linalg.svd(A)
V= V_T.T

#%%
A= [[1,-1],
    [1,1]]
A= np.array(A)
S= np.diag([2,1])
B= A@S@A.T

print(f'A= \n{A}, \nS= \n{S}, \nB= \n{B}')

A= 
[[ 1 -1]
 [ 1  1]], 
S= 
[[2 0]
 [0 1]], 
B= 
[[3 1]
 [1 3]]


In [33]:
lmda, eigV= np.linalg.eig(B)
Q, R= np.linalg.qr(B)
U,Sigma,V_T= np.linalg.svd(B)
V= V_T.T
V

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [40]:
A= [[10,1],
    [1,10]]
A= np.array(A)

lmda, eigV= np.linalg.eig(A)
print(A)
print(lmda)
print(eigV)

[[10  1]
 [ 1 10]]
[11.  9.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [41]:
A= [[1,1],
    [0,1]]
A= np.array(A)

lmda, eigV= np.linalg.eig(A)
print(A)
print(lmda)
print(eigV)

[[1 1]
 [0 1]]
[1. 1.]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


In [43]:
A= [[4,1],
    [1,4]]
A= np.array(A)

X= [[1,0,1,-1,-1,-1],
    [0,1,1,+1,-1,+1]]
X= np.array(X)

Y= A@X
print(A)
print(X)
print(Y)

[[4 1]
 [1 4]]
[[ 1  0  1 -1 -1 -1]
 [ 0  1  1  1 -1  1]]
[[ 4  1  5 -3 -5 -3]
 [ 1  4  5  3 -5  3]]


ryEx002_rowOperationsLU.py

In [44]:
import numpy as np
import scipy.linalg as sp_linalg
import pandas as pd

In [45]:
#%% ry: Row Operation for 3x3 matrix

A0= np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 10]])

A= A0.copy()

assert A[0,0] !=0 # otherwise, rowChange(A,0)

c10= -A[1,0]/A[0,0]
P10= np.array(
    [[1, 0, 0],
     [c10, 1, 0],
     [0, 0, 1]])

A= P10@A


c20= -A[2,0]/A[0,0]
P20= np.array(
    [[1, 0, 0],
     [0, 1, 0],
     [c20, 0, 1]])

A= P20@A

assert A[1,1] !=0  # otherwise, rowChange(A,1)

c21= -A[2,1]/A[1,1]
P21= np.array(
    [[1, 0, 0],
     [0, 1, 0],
     [0, c21, 1]])
A= P21@A

A1= A

P= P21@P20@P10
invP= np.linalg.inv(P)

print(f'''
A0= 
{A0}
invP= 
{invP}
A1= 
{A1}   
''')


A0= 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
invP= 
[[ 1. -0. -0.]
 [ 4.  1. -0.]
 [ 7.  2.  1.]]
A1= 
[[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  1.]]   



In [46]:
A1= np.array(
    [[1]])

A2= np.array(
    [[2,1],
     [1,2]])

A3= np.array(
    [[3, 2, 1],
     [2, 3, 2],
     [1, 2, 3]])

In [47]:
#%% ry


# Create matrix using NumPy
A= [[2,4],
    [5,7]]

A= np.array(A)

# Find matrix det, inv, matrix rank, and matrix maultiplication


detA=   np.linalg.det(A)
invA=   np.linalg.inv(A)
A_invA= A@invA

rankA= np.linalg.matrix_rank(A)

print(f'''
A= 
{A}      
detA= 
{detA}
invA= 
{invA}
A_invA= 
{A_invA}
rankA= {rankA}
''')

assert np.allclose(
    A_invA,
    np.eye(A.shape[0]))

#%%
#
# Solving linear equations using NumPy
#
b= [1,-1]
b= np.array(b)

x= np.linalg.solve(A, b)
print(f'x= {x}')

assert np.allclose(
    A@x, 
    b)


#%%

# Decomposing a matrix using SVD

U,σ,V_T= np.linalg.svd(A)


print(f'''
U= 
{U},
σ= 
{σ},
V_T= 
{V_T}      
''')

assert np.allclose(
    A,
    U@np.diag(σ)@V_T
    )



A= 
[[2 4]
 [5 7]]      
detA= 
-5.999999999999998
invA= 
[[-1.16666667  0.66666667]
 [ 0.83333333 -0.33333333]]
A_invA= 
[[1.0000000e+00 0.0000000e+00]
 [4.4408921e-16 1.0000000e+00]]
rankA= 2

x= [-1.83333333  1.16666667]

U= 
[[-0.45868991 -0.8885964 ]
 [-0.8885964   0.45868991]],
σ= 
[9.67550764 0.6201225 ],
V_T= 
[[-0.5540135  -0.83250768]
 [ 0.83250768 -0.5540135 ]]      



In [48]:
#
# Eigenvectors and Eigenvalues using NumPy
#

λ, E= np.linalg.eig(A)

print(f'''
A=
{A}
λ= 
{λ},
E= 
{E},   
''')

assert np.allclose(
    A,
    E @ np.diag(λ) @ np.linalg.inv(E)
    )



A=
[[2 4]
 [5 7]]
λ= 
[-0.62347538  9.62347538],
E= 
[[-0.83619408 -0.46462222]
 [ 0.54843365 -0.885509  ]],   



In [51]:
B= A.T@A

λ1, E1= np.linalg.eig(B)

print(f'''
B=
{B},
λ1= 
{λ1},
E1= 
{E1},   
''')

assert np.allclose(
    B,
    E1 @ np.diag(λ1) @ np.linalg.inv(E1)
    )
L= np.linalg.cholesky(A@A.T)
L


B=
[[29 43]
 [43 65]],
λ1= 
[ 0.38455192 93.61544808],
E1= 
[[-0.83250768 -0.5540135 ]
 [ 0.5540135  -0.83250768]],   



array([[4.47213595, 0.        ],
       [8.49705831, 1.34164079]])

In [52]:
#
# for symmtric matrix
#

C= np.array(
    [[2,1],
     [1,2]])

ans= {
    'rnk':  np.linalg.matrix_rank(C),
    'det':  np.linalg.det(C),
    'inv':  np.linalg.inv(C),
    'ch':   np.linalg.cholesky(C),
    'qr':   np.linalg.qr(C),
    'eig':  np.linalg.eig(C),
    'svd':  np.linalg.svd(C)
    }

print(ans)

#%%
C= np.array(
    [[3,2,1],
     [2,3,2],
     [1,2,3]])

ans= {
    'rnk':  np.linalg.matrix_rank(C),
    'det':  np.linalg.det(C),
    'inv':  np.linalg.inv(C),
    'ch':   np.linalg.cholesky(C),
    'qr':   np.linalg.qr(C),
    'eig':  np.linalg.eig(C),
    'svd':  np.linalg.svd(C)
    }

print(ans)

{'rnk': 2, 'det': 2.9999999999999996, 'inv': array([[ 0.66666667, -0.33333333],
       [-0.33333333,  0.66666667]]), 'ch': array([[1.41421356, 0.        ],
       [0.70710678, 1.22474487]]), 'qr': (array([[-0.89442719, -0.4472136 ],
       [-0.4472136 ,  0.89442719]]), array([[-2.23606798, -1.78885438],
       [ 0.        ,  1.34164079]])), 'eig': (array([3., 1.]), array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])), 'svd': (array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]]), array([3., 1.]), array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]]))}
{'rnk': 3, 'det': 8.000000000000002, 'inv': array([[ 0.625, -0.5  ,  0.125],
       [-0.5  ,  1.   , -0.5  ],
       [ 0.125, -0.5  ,  0.625]]), 'ch': array([[1.73205081, 0.        , 0.        ],
       [1.15470054, 1.29099445, 0.        ],
       [0.57735027, 1.03279556, 1.26491106]]), 'qr': (array([[-0.80178373,  0.57735027,  0.15430335],
       [-0.53452248, -0.57735027, -0.6172134 ]