In [ ]:
import numpy as np
### 直接用solve求解
# 寫出係數矩陣 A
A = np.array([
    [4, 3, 3],
    [4, 2, 5],
    [8, 8, 10],
])
# 寫出常數矩陣 B
B = np.array([350, 360, 840]).reshape(3, 1)
x = np.linalg.solve(A, B)
print("B = ")
print(x)
### 驗算
#       Ax=B
# A^(-1)Ax=A^(-1)B
#        x=A^(-1)B
# 找出係數矩陣的反矩陣 A^(-1).  "inverse A" 
A_inv = np.linalg.inv(A)
# 將 A_inv 與 B 相乘，即可得到解答
y = A_inv.dot(B)
print("利用反矩陣求解求出 B =")
print(y)
print("矩陣中元素是否對應相等:",(x==y).all())
print("-------------")

B = 
[[50.]
 [30.]
 [20.]]
利用反矩陣求解求出 B =
[[50.]
 [30.]
 [20.]]
矩陣中元素是否對應相等: True
-------------


In [ ]:
# n 變數 線性方程組 
# 利用for迴圈縮短程式
a=[3,5,10]
for n in a:
#依照n來創建 方陣A & 矩陣b 在-5~5之間隨機給值
  np.random.seed(0) 
  A= np.random.randint(-5,5,size=(n,n)).reshape(n,n)
  np.random.seed(1) 
  b= np.random.randint(-5,5,size=(n,1)).reshape(n,1)
#利用solve求解
  x= np.linalg.solve(A, b) 
  
  print( 
  f''' 
n= {n}  
A= 
{A} 
b= 
{b} 
x= 
{x} 
-------------
  ''') 

 
n= 3  
A= 
[[ 0 -5 -2]
 [-2  2  4]
 [-2  0 -3]] 
b= 
[[0]
 [3]
 [4]] 
x= 
[[-1.75806452]
 [ 0.06451613]
 [-0.16129032]] 
-------------
  
 
n= 5  
A= 
[[ 0 -5 -2 -2  2]
 [ 4 -2  0 -3 -1]
 [ 2  1  3  3 -4]
 [ 1  2  2  3 -4]
 [ 0  4  3  4 -1]] 
b= 
[[ 0]
 [ 3]
 [ 4]
 [ 0]
 [-5]] 
x= 
[[-5.05357143]
 [-1.75      ]
 [ 7.30357143]
 [-5.66071429]
 [-2.73214286]] 
-------------
  
 
n= 10  
A= 
[[ 0 -5 -2 -2  2  4 -2  0 -3 -1]
 [ 2  1  3  3 -4  1  2  2  3 -4]
 [ 0  4  3  4 -1 -2 -5 -2  0 -5]
 [-3 -2  3 -4 -2 -2 -2  2 -5 -4]
 [ 4  4 -5 -1  2 -2 -3  2 -3 -5]
 [-5 -1  0  0  1  3 -1 -4 -1  4]
 [ 3 -4 -4  2  4  4 -2  1  2 -3]
 [-5 -2  0  4 -1 -1  1 -1 -1 -2]
 [-1 -1  3 -1 -2  2  0  0 -5 -4]
 [ 0  4 -2 -5  0 -5 -4 -3 -1 -3]] 
b= 
[[ 0]
 [ 3]
 [ 4]
 [ 0]
 [-5]
 [-5]
 [-4]
 [ 2]
 [ 1]
 [ 4]] 
x= 
[[ 2.41026587]
 [-2.33689728]
 [-0.30247412]
 [ 0.90538128]
 [-2.84414544]
 [-1.88566993]
 [-0.59590749]
 [-2.26735821]
 [-0.75324469]
 [ 0.69925056]] 
-------------
  


In [ ]:
#HomeWork: 
#自己寫一個【遞迴式】的 function，來計算 Determinant ， 
#列出所有 sub-matrix 以及 其 determinant 
import numpy as np

#%% 
# when n is large, it is very slow!! 
n=2
np.random.seed(0) 
A= np.random.randint(-5,5,size=(n,n)) 
print(f'A= \n{A}') 
det= np.linalg.det(A) 
print(f'det= {det}') 
def ryDet(A): 
    n= A.shape[0] 
    if n>1: 
        i= 0 
        Bi=  np.delete(A, i, axis=0) 
        #print(f'\ni= {i}, Bi= \n{Bi}') 
        det= 0 
        for j in range(n): 
            Bij= np.delete(Bi,j, axis=1) 
            print(f'\ni,j= {i}{j}, Bij= \n{Bij}') 
            Dij= ryDet(Bij) #np.linalg.det(Bij) 
            print(f'.... Dij= {Dij}') 
            Cij= A[i,j]*Dij*(-1)**(i+j) 
            det += Cij 
        #print(f'det= {det}') 
        return det 
    elif A.shape[0]==1: 
        det= A[0,0] 
        return det 
    else: 
        return None 
det= ryDet(A) 
print(f'\ndet= {det}') 

A= 
[[ 0 -5]
 [-2 -2]]
det= -9.999999999999998

i,j= 00, Bij= 
[[-2]]
.... Dij= -2

i,j= 01, Bij= 
[[-2]]
.... Dij= -2

det= -10


In [ ]:
import scipy.linalg 

A= [[4,3], 
    [6,3]] 

A= np.array(A) 
P,L,U= scipy.linalg.lu(A) 

# 驗算 
print(P @ L @ U == A) 
np.isclose(P @ L @ U , A) 
print((P @ L @ U == A).all()) 
np.allclose(P @ L @ U , A) 



[[ True  True]
 [ True  True]]
True


True

In [ ]:
A= [[12, -51, 4],  

    [6, 167, -68], 

    [-4, 24, -41]] 

A= np.array(A) 

Q,R= np.linalg.qr(A) 