In [ ]:
import os
import sys
import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
%precision 4
plt.style.use('ggplot')

LU Decomposition and Gaussian Elimination¶

In [ ]:
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

L = np.array([[1,0,0],[2,1,0],[4,11/5,1]])
U = np.array([[1,3,4],[0,-5,-5],[0,0,-3]])
print(L.dot(U))
print(L)
print(U)

[[1. 3. 4.]
 [2. 1. 3.]
 [4. 1. 2.]]
[[1.  0.  0. ]
 [2.  1.  0. ]
 [4.  2.2 1. ]]
[[ 1  3  4]
 [ 0 -5 -5]
 [ 0  0 -3]]


In [ ]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print
print(np.dot(L, U))
print(P)
print(L)
print(U)

[[1 3 4]
 [2 1 3]
 [4 1 2]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.     0.     0.    ]
 [0.25   1.     0.    ]
 [0.5    0.1818 1.    ]]
[[4.     1.     2.    ]
 [0.     2.75   3.5   ]
 [0.     0.     1.3636]]


Cholesky Decomposition

In [ ]:
A = np.array([[1,3,5],[3,13,23],[5,23,42]])
L = la.cholesky(A)
print(np.dot(L.T, L))

print(L)
print(A)

[[ 1.  3.  5.]
 [ 3. 13. 23.]
 [ 5. 23. 42.]]
[[1. 3. 5.]
 [0. 2. 4.]
 [0. 0. 1.]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 42]]


Matrix Decompositions for PCA and Least Squares


In [ ]:
A = np.array([[0,1,1],[2,1,0],[3,4,5]])

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)


[[-0.+0.j  1.+0.j  1.+0.j]
 [ 2.+0.j  1.+0.j  0.+0.j]
 [ 3.+0.j  4.+0.j  5.+0.j]]
[ 5.8541+0.j -0.8541+0.j  1.    +0.j]


In [ ]:
A = np.array([[0,1],[-1,0]])
print(A)

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 0  1]
 [-1  0]]
[[ 0.+0.j  1.+0.j]
 [-1.+0.j  0.+0.j]]
[0.+1.j 0.-1.j]


In [ ]:

# If you know the eigenvalues must be real
# because A is a positive definite (e.g. covariance) matrix
# use real_if_close

A = np.array([[0,1,1],[2,1,0],[3,4,5]])
u, V = la.eig(A)
print(u)
print(np.real_if_close(u))

[ 5.8541+0.j -0.8541+0.j  1.    +0.j]
[ 5.8541 -0.8541  1.    ]


Stabilty and Condition Number


In [ ]:
A = np.array([[8,6,4,1],[1,4,5,1],[8,4,1,1],[1,4,3,6]])
b = np.array([19,11,14,14])
la.solve(A,b)

array([1., 1., 1., 1.])

In [ ]:
b = np.array([19.01,11.05,14.07,14.05])
la.solve(A,b)

array([-2.34 ,  9.745, -4.85 , -1.34 ])

In [ ]:
U, s, V = np.linalg.svd(A)
print(s)
print(max(s)/min(s))

[15.5457  6.9002  3.8363  0.0049]
3198.6725811991305


**Exercises**

In [1]:
import numpy as np
import scipy.linalg as la
#1. Compute the LU decomposition of the following matrix by hand and using numpy
A = np.array([[1,2,3],[2,-4,6],[3,-9,-3]])
print(A)
#First by hand

P, L, U = la.lu(A)
print(L)
print(U)

[[ 1  2  3]
 [ 2 -4  6]
 [ 3 -9 -3]]
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.4        1.        ]]
[[ 3.  -9.  -3. ]
 [ 0.   5.   4. ]
 [ 0.   0.   6.4]]


In [3]:
#2. Compute the Cholesky decomposition of the following matrix by hand and using numpy
C = np.array([[1,2,3],[2,-4,6],[3,-6,-3]])
C = np.linalg.cholesky(C)
#Matrix is not positive definite  正定矩陣才能分解

LinAlgError: ignored

In [4]:
#3. Write a function in Python to solve a system
#using SVD decomposition. Your function should take A and b as input and return x
#Your function should include the following:

#First, check that A is invertible - return error message if it is not
#Invert A using SVD and solve return x
#Test your function for correctness.
def svdsolver(A,b):
    U, s, V = np.linalg.svd(A)
    if np.prod(s) == 0:
       print("Matrix is singular")
    else:
       return np.dot(np.dot((V.T).dot(np.diag(s**(-1))), U.T),b)
A = np.array([[1,1],[1,2]])
b = np.array([3,1])
print(np.linalg.solve(A,b))
print(svdsolver(A,b))

[ 5. -2.]
[ 5. -2.]
