# ryEx000.ipynb
- 先熟悉一下環境


In [1]:
x= 8
y= 22
z= x+y

x,y,z,y-x*y

(8, 22, 30, -154)

In [2]:
def f(x,y):
    z= x+y
    return z

f(1, 5)

6

In [5]:
def add(x,y):
    z= x+y
    return z
def sub(x,y):
    z= x-y
    return z
def mul(x,y):
    z= x*y
    return z
def div(x,y):
    z= x/y
    return z

a= add(1,2)
s= sub(1,2)
m= mul(1,2)
d= div(1,2)
j= sub(mul(6,8),8)
a,s,m,d,j

(3, -1, 2, 0.5, 40)

In [8]:
class Number:
    
    def __init__(self,x=0):
        self.x= x
        
    def add(self,y):
        z= self.x + y
        return z
    
    def sub(self,y):
        z= self.x - y
        return z
    
    def mul(self,y):
        z= self.x * y
        return z
    
    def div(self,y):
        z= self.x / y
        return z

n= Number(100)
a= n.add(1)
s= n.sub(1)
m= n.mul(1)
d= n.div(1)
n, n.x, a, s, m, d

(<__main__.Number at 0x7f739ed313d0>, 100, 101, 99, 100, 100.0)

In [12]:
# 運用繼承的觀念，繼續擴充 物件內涵
# dunder (double under，雙底線) __xxx__

class Number(Number):
        
    def __add__(self,y):
        z= self.add(y)
        return z
    def __sub__(self,y):
        z= self.sub(y)
        return z
    def __mul__(self,y):
        z= self.mul(y)
        return z
    def __truediv__(self,y): # 這個除法的名稱比較特殊
        z= self.div(y)
        return z


n= Number(100)
a= n.add(5)
s= n.sub(5)
m= n.mul(2)
d= n.div(3)  
n, n.x, a, s, m, d

(<__main__.Number at 0x7f739ecb5910>, 100, 105, 95, 200, 33.333333333333336)

In [14]:
a= n.__add__(2)
s= n.__sub__(2)
m= n.__mul__(2)
d= n.__truediv__(6)
n, n.x, a, s, m, d

(<__main__.Number at 0x7f739ecb5910>, 100, 102, 98, 200, 16.666666666666668)

In [15]:
a= n+2
s= n-2
m= n*2
d= n/7
n, n.x, a, s, m, d

(<__main__.Number at 0x7f739ecb5910>, 100, 102, 98, 200, 14.285714285714286)

In [17]:
class Number(Number):
    
    # print our string object
    def __repr__(self):      # 更改 此 物件的 print() 結果。 以字串型態送出去。
        return f'{self.x}'
    pass
    
    
n= Number(9455)
n


9455

In [18]:
type(n)

__main__.Number

In [ ]:
# 向量的加減乘除四則運算

In [28]:
x= [1,2,3]
y= [10,20,30]
x+y

[1, 2, 3, 10, 20, 30]

In [29]:
x+2*y, 

([1, 2, 3, 10, 20, 30, 10, 20, 30],)

In [ ]:

# Python List 的 運算 +, -, * , / 不是 我們在數學上向量、矩陣、、、等的定義方式。
# 自己定義一個向量物件，使其符合數學上的定義！

In [21]:
class Vector:
    def __init__(self, x):
        self.x= x
        
    def add(self,y):    
        z= [xi+yi for xi,yi in zip(self.x, y)]
        return z

v= Vector([1,2,3,4])
v.add([10,20,30,40])

[11, 22, 33, 44]

In [ ]:
# 把它擴展成 +, - , *, / 都可以


In [23]:
class Vector:
    def __init__(self, x):
        self.x= x
        
    def add(self,y):    
        z= [xi+yi for xi,yi in zip(self.x, y)]
        return z
    def sub(self,y):    
        z= [xi-yi for xi,yi in zip(self.x, y)]
        return z
    def mul(self,y):    
        z= [xi*yi for xi,yi in zip(self.x, y)]
        return z
    def div(self,y):    
        z= [xi/yi for xi,yi in zip(self.x, y)]
        return z
    
    def __add__(self,y):    
        z= self.add(y)
        return z
    def __sub__(self,y):    
        z= self.sub(y)
        return z
    def __mul__(self,y):    
        z= self.mul(y)
        return z
    def __truediv__(self,y):    
        z= self.div(y)
        return z

v= Vector([1,2,3,4])
v, v.x

(<__main__.Vector at 0x7f739ed31190>, [1, 2, 3, 4])

In [30]:
a= v + [10,20,30,40]
s= v - [10,20,30,40]
m= v * [10,20,30,40]
d= v / [10,20,30,40]
v.x, a, s, m, d

([1, 2, 3, 4],
 [11, 22, 33, 44],
 [-9, -18, -27, -36],
 [10, 40, 90, 160],
 [0.1, 0.1, 0.1, 0.1])

# Numpy 就是把我們以上作的事情再進一步延伸.... 成為一個偉大的模組 (module)

# Introduction to Linear Algebra with NumPy

- https://towardsdatascience.com/introduction-to-linear-algebra-with-numpy-79adeb7bc060


In [31]:
import numpy as np


In [35]:
v= [10, 5, 1, 4]
v

[10, 5, 1, 4]

In [36]:
v= np.array(v)
v

array([10,  5,  1,  4])

In [37]:
v.shape

(4,)

In [38]:
A= [[1,2,3,4],
    [5,6,7,8]]
A

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [70]:
A= np.array(A)
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
A.shape

(2, 4)

In [49]:
T=[ [1,2,3,4],
      [5,6,7,8],
   [9,10,11,12],
   [13,14,15,16]]
T

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [50]:
T= np.array(T)
T

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [51]:
T.shape

(4, 4)

In [75]:
T= T.reshape((2,2,4))
T

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [76]:
T.shape

(2, 2, 4)

In [53]:
T[0]

array([1, 2, 3, 4])

In [54]:
T[1]

array([5, 6, 7, 8])

In [55]:
v.ndim

1

In [56]:
A.ndim

2

In [57]:
T.ndim

2

![](https://miro.medium.com/max/555/0*Vh-pKXTJsdL-9FT0.png)

In [63]:
T4d= T.reshape(2,2,2,2)
T4d


array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [64]:
T4d.shape

(2, 2, 2, 2)

In [65]:
v, A, T, T4d

(array([10,  5,  1,  4]), array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]), array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]]))

In [66]:
v

array([10,  5,  1,  4])

In [67]:
v14= v.reshape(1,4)
v14

array([[10,  5,  1,  4]])

In [68]:
v41= v.reshape(4,1)
v41

array([[10],
       [ 5],
       [ 1],
       [ 4]])

In [69]:
v.shape, v14.shape, v41.shape

((4,), (1, 4), (4, 1))

# Vector Operations

We have covered the basic structures. Now it is time to discuss basic operations that can be done on these structures.


In [93]:
Q = [0,1,2,3,4,5,6,7,8,9]
Q = np.array(Q)
Q

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
Q= Q.reshape(5,2)
Q

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [95]:
Q=(3*Q/2+5)*4
Q

array([[20., 26.],
       [32., 38.],
       [44., 50.],
       [56., 62.],
       [68., 74.]])